# DO NOT EDIT: This file is automatically generated by fauxgen.
# Any changes made to this file will be overwritten.

import datetime
from typing import Any, TypedDict

import fauxgen as f


class ArticleBaseRecord(TypedDict):
    """A data structure representing ArticleBase entries."""
    id: int
    title: str
    author_id: int


def article_base_record(
    *,
    id: int | f.Unset = f.UNSET,
    title: str | f.Unset = f.UNSET,
    author_id: int | f.Unset = f.UNSET,
    seed_: int | None = None,
) -> ArticleBaseRecord:
    """Creates a mock ArticleBase entry with randomized values.

    Each field is generated with appropriate constraints and validation rules.
    Values can be overridden by providing specific field values.

    Args:
        id (int): Unique identifier for the article
        title (str): Article title
        author_id (int): Unique identifier of the article's author
        seed_ (int | None): Seed value for deterministic data generation.
                            The same seed will always produce the same values.

    Returns:
        ArticleBaseRecord: A new mock entry with generated data.
    """
    return {
        "id": f.Unset.unwrap_or_else(id, lambda: f.gen_int(ge=1, le=101, seed=seed_)),
        "title": f.Unset.unwrap_or_else(title, lambda: f.gen_string(min_length=5, max_length=10, seed=seed_)),
        "author_id": f.Unset.unwrap_or_else(author_id, lambda: f.gen_int(ge=1, le=101, seed=seed_)),
    }


class BlogArticleRecord(TypedDict):
    """A data structure representing BlogArticle entries."""
    id: int
    title: str
    author_id: int
    content: str | None
    published_at: datetime.datetime | None
    is_published: bool
    tags: str | None


def blog_article_record(
    *,
    id: int | f.Unset = f.UNSET,
    title: str | f.Unset = f.UNSET,
    author_id: int | f.Unset = f.UNSET,
    content: str | None | f.Unset = f.UNSET,
    published_at: datetime.datetime | None | f.Unset = f.UNSET,
    is_published: bool | f.Unset = f.UNSET,
    tags: str | None | f.Unset = f.UNSET,
    seed_: int | None = None,
) -> BlogArticleRecord:
    """Creates a mock BlogArticle entry with randomized values.

    Each field is generated with appropriate constraints and validation rules.
    Values can be overridden by providing specific field values.

    Args:
        id (int): Unique identifier for the article
        title (str): Article title
        author_id (int): Unique identifier of the article's author
        content (str | None): Main body of the blog article
        published_at (datetime.datetime | None): Timestamp when the article was published
        is_published (bool): Flag indicating whether the blog is publicly available
        tags (str | None): Comma-separated tags for the blog
        seed_ (int | None): Seed value for deterministic data generation.
                            The same seed will always produce the same values.

    Returns:
        BlogArticleRecord: A new mock entry with generated data.
    """
    return {
        "id": f.Unset.unwrap_or_else(id, lambda: f.gen_int(ge=1, le=101, seed=seed_)),
        "title": f.Unset.unwrap_or_else(title, lambda: f.gen_string(min_length=5, max_length=10, seed=seed_)),
        "author_id": f.Unset.unwrap_or_else(author_id, lambda: f.gen_int(ge=1, le=101, seed=seed_)),
        "content": f.Unset.unwrap_or_else(content, lambda: f.gen_string(min_length=5, max_length=10, seed=seed_)),
        "published_at": f.Unset.unwrap_or_else(published_at, lambda: f.gen_datetime(from_datetime=datetime.datetime(2020, 1, 1), to_datetime=datetime.datetime(2021, 1, 1), seed=seed_)),
        "is_published": f.Unset.unwrap_or_else(is_published, lambda: f.gen_bool(seed=seed_)),
        "tags": f.Unset.unwrap_or_else(tags, lambda: f.gen_string(min_length=5, max_length=10, seed=seed_)),
    }
