# DO NOT EDIT: This file is automatically generated by fauxgen.
# Any changes made to this file will be overwritten.

import datetime
from typing import Any, TypedDict

import fauxgen as f


class PandasModelRecord(TypedDict):
    """A data structure representing PandasModel entries."""
    id: int
    created_at: datetime.datetime


def pandas_model_record(
    *,
    id: int | f.Unset = f.UNSET,
    created_at: datetime.datetime | f.Unset = f.UNSET,
    seed_: int | None = None,
) -> PandasModelRecord:
    """Creates a mock PandasModel entry with randomized values.

    Each field is generated with appropriate constraints and validation rules.
    Values can be overridden by providing specific field values.

    Args:
        id (int): Unique identifier
        created_at (datetime.datetime): Creation timestamp
        seed_ (int | None): Seed value for deterministic data generation.
                            The same seed will always produce the same values.

    Returns:
        PandasModelRecord: A new mock entry with generated data.
    """
    return {
        "id": f.Unset.unwrap_or_else(id, lambda: f.gen_int(ge=1, le=101, seed=seed_)),
        "created_at": f.Unset.unwrap_or_else(created_at, lambda: f.gen_datetime(from_datetime=datetime.datetime(2020, 1, 1), to_datetime=datetime.datetime(2021, 1, 1), seed=seed_)),
    }
